### ISSUE TITLE
tests failing to build on stackage nightly (GHC 8.10.1)

### ISSUE THREAD

**Issue by cdornan** [takenobu-hs/ghci-hexcalc#2]
On Stackage Nightly we are seeing the following failures while trying to build the test suite. We have marked the package as expecting test failures. Let us know if you locate a fix for the issue and want the package tested again.

---

```
Test suite failure for package ghci-hexcalc-0.1.1.0
    test-ghci-hexcalc:  exited with: ExitFailure 1
Full log available at /var/stackage/work/unpack-dir/.stack-work/logs/ghci-hexcalc-0.1.1.0-test.log



    src/Data/GHex.hs:143:1: error:
        Could not load module ‘Data.Binary.Put’
        It is a member of the hidden package ‘binary-0.8.8.0’.
        You can run ‘:set -package binary’ to expose it.
        (Note: this unloads all the modules in the current scope.)
        Use -v (or `:set -v` in ghci) to see a list of the files searched for.
        |
    143 | import           Data.Binary.Put (runPut, putWord32le, putWord64le,
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...

    src/Data/GHex.hs:145:1: error:
        Could not load module ‘Data.Binary.Get’
        It is a member of the hidden package ‘binary-0.8.8.0’.
        You can run ‘:set -package binary’ to expose it.
        (Note: this unloads all the modules in the current scope.)
        Use -v (or `:set -v` in ghci) to see a list of the files searched for.
        |
    145 | import           Data.Binary.Get (runGet, getFloatle, getDoublele,
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by takenobu-hs** [comment]
Thank you for your hard work.

I tried build and test as following command, but I couldn't reproduce the error.

```
$ stack unpack ghci-hexcalc-0.1.1.0
$ cd ghci-hexcalc-0.1.1.0
$ rm -f stack.yaml && stack init --resolver nightly
$ stack build --resolver nightly --haddock --test --bench --no-run-benchmarks
```

Could you advise me how to reproduce the error?

**Comment by cdornan** [comment]
It is the test suite that is failing to build &mdash; could you try `stack test`?

**Comment by takenobu-hs** [comment]
Thank you for taking your time.

I also tried `stack test`, but it passed as following:

```
$ stack test

Warning: Failed to decode module interface:
         /home/user/ghci-hexcalc-0.1.1.0/.stack-work/dist/x86_64-linux/Cabal-3.2.0.0/build/Data/GHex.hi
         Decoding failure: Invalid magic: e49ceb0f
ghci-hexcalc> test (suite: test-ghci-hexcalc)

Examples: 143  Tried: 143  Errors: 0  Failures: 0

ghci-hexcalc> Test suite test-ghci-hexcalc passed
```

I'm using Ubuntu 18.04LTS. My stack version is 2.3.1.
Is there another way to reproduce it?

**Comment by cdornan** [comment]
Hmn, @DanBurton, unless you have an idea as to what has happened, maybe we should enable tests again in case the problem has fixed itself.

**Comment by DanBurton** [comment]
I cannot reproduce this locally; it looks like it is an issue specific to the setup on Stackage's build server.  I'm not sure why the `binary` package would be hidden but I'll look into it.

**Comment by takenobu-hs** [comment]
Thank you for dealing this!
